48 add hash map page
WomenWhoCode/wwcsf-algos pull request #62
Opened 2020-11-05 00:19 UTC by arch92

Added Hash Map Page.

2020-11-05 00:19 UTC, arch92 commented
@elaguerta Can you review this?

2020-11-05 12:19 UTC, elaguerta requested changes
Hey Archana, this is looking great! Please address the following:
1. Add a folder to `/code-examples` called `hashmaps`. This will be where people can submit code examples. 
2. I added suggestions in-line to provide correct links to the new code-examples/hashmaps  folder, please commit these. 
3. Add a link to this page to the main README, in this section:
https://github.com/WomenWhoCode/wwcsf-algos#3-resources-and-problem-sets-by-category
4. Add this problem to the Hard section: https://leetcode.com/problems/maximum-frequency-stack/
5. Change your PR from draft status to normal, so we can merge it in!

Thank you!

2020-11-05 12:19 UTC, elaguerta commented on topics/Hashmaps.md
> +[Longest Substring Without Repeating Characters](https://leetcode.com/problems/longest-substring-without-repeating-characters/) | [leetcode's endorsed solution](https://leetcode.com/problems/longest-
```suggestion
[Longest Substring Without Repeating Characters](https://leetcode.com/problems/longest-substring-without-repeating-characters/) | [leetcode's endorsed solution](https://leetcode.com/problems/longest-substring-without-repeating-characters/solution/) | please contribute your solution to our [code examples!]((https://github.com/WomenWhoCode/wwcsf-algos/tree/master/code-examples/hashmaps)
```

2020-11-05 12:19 UTC, elaguerta commented on topics/Hashmaps.md
> +[Top K Frequent Words](https://leetcode.com/problems/top-k-frequent-words/) | [leetcode's endorsed solution](https://leetcode.com/problems/top-k-frequent-words/solution/) | please contribute your sol
```suggestion
[Top K Frequent Words](https://leetcode.com/problems/top-k-frequent-words/) | [leetcode's endorsed solution](https://leetcode.com/problems/top-k-frequent-words/solution/) | please contribute your solution to our [code examples!]((https://github.com/WomenWhoCode/wwcsf-algos/tree/master/code-examples/hashmaps)
```

2020-11-05 12:19 UTC, elaguerta commented on topics/Hashmaps.md
> +[LFU Cache](https://leetcode.com/problems/lfu-cache/) | [leetcode's endorsed solution](https://leetcode.com/problems/longest-substring-without-repeating-characters/solution/) | please contribute your
```suggestion
[LFU Cache](https://leetcode.com/problems/lfu-cache/) | [leetcode's endorsed solution](https://leetcode.com/problems/longest-substring-without-repeating-characters/solution/) | please contribute your solution to our [code examples!]((https://github.com/WomenWhoCode/wwcsf-algos/tree/master/code-examples/hashmaps)
```

2020-11-06 23:09 UTC, elaguerta approved these changes
Hey @arch92 I completed the revisions, so you're done! Thanks so much for your contribution. I'm looking forward to sharing this with the group next week!

2020-11-06 23:09 UTC, merged