Added content for stacks and queues
WomenWhoCode/wwcsf-algos pull request #68
Opened 2021-03-10 19:14 UTC by spriyam

Added stacks-queues.md page. Updated readme.md to add the stacks-queues page in it.

2021-03-18 18:14 UTC, elaguerta requested changes
Great job! I liked your resources selection - that CMU article is great.
Nice problem selection too, covers the important techniques and topics.
See suggestions in-line. The only errors I found were the last too problems were missing solution links (they had the wrong links, probably left over from the template). 
Once you have resolved the comments, please feel free to merge it in, it does not need a re-review from me. Thank you for this contribution!

2021-03-18 18:14 UTC, elaguerta commented on topics/stacks-queues.md
> +[Min Stack](https://leetcode.com/problems/min-stack/) | [Solution discussion](https://leetcode.com/problems/min-stack/solution/) | please contribute your solution to our [code examples!](https://gith
It looks like the solution for Min Stack is behind the paywall. I suggest directing to the solution discussion instead:
```suggestion
[Min Stack](https://leetcode.com/problems/min-stack/) | [Solution discussion](https://leetcode.com/problems/min-stack/discuss/?currentPage=1&orderBy=hot&query=) | please contribute your solution to our [code examples!](https://github.com/WomenWhoCode/wwcsf-algos/tree/master/code-examples/)
```

2021-03-18 18:14 UTC, elaguerta commented on topics/stacks-queues.md
> +[Binary Tree zig zag level order tree traversal ](https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/) | [Solution discussion](https://leetcode.com/problems/binary-tree-zigzag-lev
Same thing here, solution behind the paywall. 
```suggestion
[Binary Tree zig zag level order tree traversal ](https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/) | [Solution discussion](https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/discuss/?currentPage=1&orderBy=hot&query=) | please contribute your solution to our [code examples!](https://github.com/WomenWhoCode/wwcsf-algos/tree/master/code-examples/)
```

2021-03-18 18:14 UTC, elaguerta commented on topics/stacks-queues.md
> +[Binary Tree inorder traversal](https://leetcode.com/problems/binary-tree-inorder-traversal/) | [Solution discussion](https://leetcode.com/problems/binary-tree-inorder-traversal/solution/) | please c
I'm sure no one will notice except for me, but let's label the solution 'solution link' to let people know it's the Solution and not the Discussion :)

```suggestion
[Binary Tree inorder traversal](https://leetcode.com/problems/binary-tree-inorder-traversal/) | [Solution link](https://leetcode.com/problems/binary-tree-inorder-traversal/solution/) | please contribute your solution to our [code examples!](https://github.com/WomenWhoCode/wwcsf-algos/tree/master/code-examples/)
```

2021-03-18 18:14 UTC, elaguerta commented on topics/stacks-queues.md
> +[Basic Calculator - II](https://leetcode.com/problems/basic-calculator-ii/) | [Solution discussion](https://leetcode.com/problems/basic-calculator-ii/solution/) | please contribute your solution to o
Same thing here
```suggestion
[Basic Calculator - II](https://leetcode.com/problems/basic-calculator-ii/) | [Solution link](https://leetcode.com/problems/basic-calculator-ii/solution/) | please contribute your solution to our [code examples!](https://github.com/WomenWhoCode/wwcsf-algos/tree/master/code-examples/)
```

2021-03-18 18:14 UTC, elaguerta commented on topics/stacks-queues.md
> +[Trapping rain water](https://leetcode.com/problems/trapping-rain-water/) | [Solution discussion](https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/discuss/?currentPage=1&orderBy=
This one is an error, Trapping Rain Water is missing the solution link
```suggestion
[Trapping rain water](https://leetcode.com/problems/trapping-rain-water/) | [Solution link](https://leetcode.com/problems/trapping-rain-water/solution/) | please contribute your solution to our [code examples!](https://github.com/WomenWhoCode/wwcsf-algos/tree/master/code-examples/)
```

2021-03-18 18:14 UTC, elaguerta commented on topics/stacks-queues.md
> +[Largest rectangle in histogram](https://leetcode.com/problems/largest-rectangle-in-histogram/) | [Solution discussion](https://leetcode.com/problems/wiggle-sort-ii/discuss/?currentPage=1&orderBy=mos
Same thing here, missing solution link
```suggestion
[Largest rectangle in histogram](https://leetcode.com/problems/largest-rectangle-in-histogram/) | [Solution discussion](https://leetcode.com/problems/largest-rectangle-in-histogram/discuss/?currentPage=1&orderBy=hot&query=) | please contribute your solution to our [code examples!](https://github.com/WomenWhoCode/wwcsf-algos/tree/master/code-examples/)
```

2021-03-19 21:23 UTC, spriyam commented
Incorporated all the review comments

2021-03-20 20:39 UTC, merged